add_newline = false
command_timeout = 1000
scan_timeout = 30
format = "$directory$git_branch$git_status$nodejs$python$dotnet$bun$docker_context$kubernetes$cmd_duration$line_break$character"

[directory]
truncation_length = 4
truncate_to_repo = true
style = "blue"

[git_branch]
symbol = "ï˜ "
style = "purple"

[git_status]
style = "yellow"
format = '([\[$all_status$ahead_behind\]]($style) )'

[nodejs]
symbol = "îœ˜ "
format = "via [$symbol($version )]($style)"
style = "green"

[python]
symbol = "î˜† "
format = "via [$symbol($version )]($style)"
style = "yellow"

[dotnet]
symbol = "ó°ª® "
format = "via [$symbol($version )]($style)"
style = "blue"

[bun]
symbol = "ğŸ¥Ÿ "
format = "via [$symbol($version )]($style)"
style = "red"

[docker_context]
symbol = "ïŒˆ "
format = "on [$symbol$context]($style) "
style = "blue"
only_with_files = true

[kubernetes]
symbol = "âˆ "
format = "on [$symbol$context( ($namespace))]($style) "
style = "cyan"
disabled = false

[cmd_duration]
min_time = 500
format = "took [$duration]($style) "
style = "dimmed white"

[character]
success_symbol = "[â¯](green)"
error_symbol = "[â¯](red)"
vicmd_symbol = "[â®](green)"
