add_newline = false
format = "$directory$git_branch$git_status$cmd_duration$line_break$character"

[directory]
truncation_length = 4
truncate_to_repo = true
style = "blue"

[git_branch]
symbol = " "
style = "purple"

[git_status]
style = "yellow"
format = '([\[$all_status$ahead_behind\]]($style) )'

[cmd_duration]
min_time = 500
format = "took [$duration]($style) "
style = "dimmed white"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"
